/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 pandaAnimation.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/pandaAnimation.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
          <skinnedMesh name="Retopo_Player_SkinPandaVariant1_0004" geometry={nodes.Retopo_Player_SkinPandaVariant1_0004.geometry} material={materials.Material} skeleton={nodes.Retopo_Player_SkinPandaVariant1_0004.skeleton} />
          <skinnedMesh name="Vert002" geometry={nodes.Vert002.geometry} material={materials.Material} skeleton={nodes.Vert002.skeleton} />
          <skinnedMesh name="Vert" geometry={nodes.Vert.geometry} material={materials.Material} skeleton={nodes.Vert.skeleton} morphTargetDictionary={nodes.Vert.morphTargetDictionary} morphTargetInfluences={nodes.Vert.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pandaAnimation.gltf')
